MVC-ModMaZa/Models/DbSınıflar/Faturalar.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using System.Linq;
using System.Web;

namespace MVC_ModMaZa.Models.DbSınıflar
{
    public class Faturalar
    {
        [Key]
        public int FaturaID { get; set; }
        [Column(TypeName = "Char")]
        [StringLength(1)]
        public string FaturaSeriNo { get; set; }
        [Column(TypeName = "Varchar")]
        [StringLength(6)]
        public string FaturaSıraNo { get; set; }
        public DateTime Tarih { get; set; }
        [Column(TypeName = "Varchar")]
        [StringLength(60)]
        public string VergiDairesi { get; set; }
        [Column(TypeName = "char")]
        [StringLength(5)]
        public string Saat { get; set; }

        [Column(TypeName = "Varchar")]
        [StringLength(30)]
        public string TeslimEden { get; set; }
        [Column(TypeName = "Varchar")]
        [StringLength(30)]
        public string TeslimAlan { get; set; }
        public decimal Toplam { get; set; }
        public ICollection <FaturaKalem> faturaKalems { get; set; }

    }
}

MVC-ModMaZa/Controllers/FaturalarController.cs
using MVC_ModMaZa.Models.DbSınıflar;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace MVC_ModMaZa.Controllers
{
    public class FaturalarController : Controller
    {
        // GET: Faturalar
        Contex db = new Contex();
        public ActionResult Index()
        {
            var deger = db.faturalars.ToList();
            return View(deger);
        }
        [HttpGet]
        public ActionResult FaturaEkle()
        {

            return View();
        }
                                 

        [HttpPost]
       public ActionResult FaturaEkle( Faturalar f)
        {
            db.faturalars.Add(f);
            db.SaveChanges();
            return RedirectToAction("Index");
        }
        public ActionResult FaturaGetir(int id)
        {
            var faturalar = db.faturalars.Find(id);
            return View("FaturaGetir", faturalar);
        }

        public ActionResult FaturaGuncelle(Faturalar f)
        {
            var fat = db.faturalars.Find(f.FaturaID);
            fat.FaturaSeriNo = f.FaturaSeriNo;
            fat.FaturaSıraNo = f.FaturaSıraNo;
            fat.Saat = f.Saat;
            fat.Tarih = f.Tarih;
            fat.TeslimAlan = f.TeslimAlan;
            fat.TeslimEden = f.TeslimEden;
            fat.VergiDairesi = f.VergiDairesi;
            db.SaveChanges();

            return RedirectToAction("Index");
        }
        public ActionResult FaturaDetay(int id)
        {
            var deger = db.faturaKalems.Where(x => x.FaturaID == id).ToList();
            return View(deger);
        }
        [HttpGet]
        public ActionResult YeniKalem()
        {
            return View();
        }
        [HttpPost]
        public ActionResult YeniKalem(FaturaKalem p)
        {
           db.faturaKalems.Add(p);
            db.SaveChanges();
            return RedirectToAction("Index");
        }
    }
}

MVC-ModMaZa/Views/Faturalar/FaturaDetay.cshtml
@using MVC_ModMaZa.Models.DbSınıflar
@model List<FaturaKalem>
@{
    ViewBag.Title = "FaturaDetay";
    Layout = "~/Views/Shared/_AdminLayout.cshtml";
}
<br />
<h2>Fatura Kalem Sayfası</h2>

<br />
<ol class="breadcrumb mb-4">
    <li class="breadcrumb-item active"></li>
</ol>

<table class="table table-hover">
    <tr>
        <th>ID</th>
        <th>Açıklama</th>
        <th>Miktar</th>
        <th>Birim Fiyat</th>
        <th>Tutar</th>
        <th>Detaylar</th>

    </tr>

    @foreach (var item in Model)
    {
        <tr>
            <td>@item.FaturaKalemid</td>
            <td>@item.Açiklama</td>
            <td>@item.Miktar</td>
            <td>@item.BirimFiyatı</td>
            <td>@item.Tutar</td>
            <td>
                <a href="/departman/DepartmanPersonelSatıs/@item.FaturaKalemid" class="btn btn-default" style="background-color:aquamarine">
                    Satışlar
                </a>
            </td>
        </tr>
    }



</table>
<a href="/Faturalar/YeniKalem" class="btn btn-default"style="background-color:darksalmon">Yeni Kalem Girişi</a>

MVC-ModMaZa/Views/Faturalar/FaturaEkle.cshtml
@model MVC_ModMaZa.Models.DbSınıflar.Faturalar
@{
    ViewBag.Title = "FaturaEkle";
    Layout = "~/Views/Shared/_AdminLayout.cshtml";
}



<br />
<h2>Yeni Fatura Sayfası</h2>
<br />

<form class="form-group" method="post">
    <h4>Fatura Seri No</h4>
    @Html.TextBoxFor(x => x.FaturaSeriNo, new { @class = "form-control" })
    <br />
    <h4>Fatura Sıra no  </h4>
    @Html.TextBoxFor(x => x.FaturaSıraNo, new { @class = "form-control" })
    <br />
    <h4>Tarih </h4>
    @Html.TextBoxFor(x => x.Tarih, new { @class = "form-control" })
    <br />
    <h4>Saat</h4>
    @Html.TextBoxFor(x => x.Saat, new { @class = "form-control" })
    <br />
    <h4>Vergi Dairesi</h4>
    @Html.TextBoxFor(x => x.VergiDairesi, new { @class = "form-control" })
    <h4>Teslim Eden</h4>
    @Html.TextBoxFor(x => x.TeslimEden, new { @class = "form-control" })
    <br />
    <h4>Teslim Alan</h4>
    @Html.TextBoxFor(x => x.TeslimAlan, new { @class = "form-control" })
    <br />


    <br />


    <button class=" btn btn-primary"> Kaydet   </button>
</form>

MVC-ModMaZa/Views/Faturalar/FaturaGetir.cshtml
@model MVC_ModMaZa.Models.DbSınıflar.Faturalar
@{
    ViewBag.Title = "FaturaGetir";
    Layout = "~/Views/Shared/_AdminLayout.cshtml";
}
<br />
<h2>Fatura Güncelle </h2>
<br />

@using (Html.BeginForm("FaturaGuncelle", "Faturalar", FormMethod.Post))
{
    @Html.HiddenFor(x => x.FaturaID)
    <h4>Seri No</h4>
    @Html.TextBoxFor(x => x.FaturaSeriNo, new { @class = "form-control" })
    <br />
    <h4>Sıra No</h4>
    @Html.TextBoxFor(x => x.FaturaSıraNo, new { @class = "form-control" })
    <br />
    <h4>Vergi Dairesi</h4>
    @Html.TextBoxFor(x => x.VergiDairesi, new { @class = "form-control" })
    <br />
    <h4>Tarih</h4>
    @Html.TextBoxFor(x => x.Tarih, new { @class = "form-control" })
    <br />
    <h4>Saat</h4>
    @Html.TextBoxFor(x => x.Saat, new { @class = "form-control" })
    <br />
    <h4>Teslim Eden</h4>
    @Html.TextBoxFor(x => x.TeslimEden, new { @class = "form-control" })
    <br />
    <h4>Tesim Alan</h4>
    @Html.TextBoxFor(x => x.TeslimAlan, new { @class = "form-control" })
    <br />
    <button class=" btn btn-warning"> Güncelle   </button>

}

MVC-ModMaZa/Views/Faturalar/Index.cshtml
@using MVC_ModMaZa.Models.DbSınıflar
@model List<Faturalar>
@{
    ViewBag.Title = "Index";
    Layout = "~/Views/Shared/_AdminLayout.cshtml";
}

<table class="table table-bordered" style="margin-top:20px; ">
    <tr>
        <th>
            ID
        </th>
        <th>
            Seri no
        <th>
            Sıra No
        <th>
            Vergi Dairesi
        </th>
        <th>
            Tarih
        </th>
        <th>
            Saat
        </th>
        <th>
            Toplam
        </th>
        <th>
            Teslim Eden
        </th>
        <th>
            Teslim Alan
        </th>
        <th>
            Toplam
        </th>
        <th>
            Güncelle
        </th>
        <th>
            Detaylar
        </th>

    </tr>
    @foreach (var item in Model)
    {


        <tr>
            <td>
                @item.FaturaID
            </td>
            <td> @item.FaturaSeriNo</td>
            <td> @item.FaturaSıraNo</td>
            <td> @item.VergiDairesi</td>
            <td> @item.Tarih</td>
            <td> @item.Saat</td>
            <td> @item.TeslimEden</td>
            <td> @item.TeslimAlan</td>
            <td></td>

            <td>
                <a href="/Faturalar/FaturaGetir/@item.FaturaID" class="btn btn-success">Güncelle</a>
            </td>
            <td>
                <a href="/Faturalar/FaturaDetay/@item.FaturaID" class="btn btn btn-outline-primary">Detaylar</a>
            </td>
        </tr>

    }

</table>
<a class="btn btn-info" href="/Faturalar/FaturaEkle">Yeni Fatura Girişi</a>

MVC-ModMaZa/Views/Faturalar/YeniKalem.cshtml
@model MVC_ModMaZa.Models.DbSınıflar.FaturaKalem
@{
    ViewBag.Title = "YeniKalem";
    Layout = "~/Views/Shared/_AdminLayout.cshtml";
}



<br />
<h2>Yeni Kalem Sayfası</h2>
<br />

<form class="form-group" method="post">
    <h4>Açıklama</h4>
    @Html.TextBoxFor(x => x.Açiklama, new { @class = "form-control" })
    <br />
    <h4>Miktar </h4>
    @Html.TextBoxFor(x => x.Miktar, new { @class = "form-control" })
    <br />
    <h4>Birim Fiyat </h4>
    @Html.TextBoxFor(x => x.BirimFiyatı, new { @class = "form-control" })
    <br />
    <h4>Tutar</h4>
    @Html.TextBoxFor(x => x.Tutar, new { @class = "form-control" })
    <br />
    <h4>Tutar</h4>
    @Html.TextBoxFor(x => x.FaturaID, new { @class = "form-control" })
    <br />
    <button class=" btn btn-primary"> Kaydet   </button>
</form>