MVC-ModMaZa/Controllers/SatisController.cs
using MVC_ModMaZa.Models.DbSınıflar;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace MVC_ModMaZa.Controllers
{
    public class SatisController : Controller
    {
        // GET: Satis
        Contex db = new Contex();
        public ActionResult Index()
        {
            var deger = db.satisHarekets.ToList();
            return View(deger);
        }
        [HttpGet]
        public ActionResult YeniSatiş()
        {
            List<SelectListItem> deger = (from x in db.uruns.ToList()
                                          select new SelectListItem
                                          {

                                              Text = x.UrunAd,
                                              Value = x.ID.ToString()

                                          }).ToList();
            List<SelectListItem> deger1 = (from x in db.carilers.ToList()
                                           select new SelectListItem
                                           {
                                               Text = x.CariAD + " " + x.CariSoyad,
                                               Value = x.CariID.ToString()
                                           }).ToList();
            List<SelectListItem> deger2 = (from x in db.personels.ToList()
                                           select new SelectListItem
                                           {
                                               Text = x.PersonelAd + " " + x.PersonelSoyad,
                                               Value = x.ID.ToString()
                                           }).ToList();

            ViewBag.dgr1 = deger1;
            ViewBag.dgr2 = deger2;
            ViewBag.dgr = deger;
            return View();
        }
        [HttpPost]
        public ActionResult YeniSatiş(SatisHareket s)
        {
            s.Tarih =DateTime.Parse (DateTime.Now.ToShortDateString());
            db.satisHarekets.Add(s);
            db.SaveChanges();
            return RedirectToAction("Index");
        }
        public ActionResult SatisGetir(int id)
        {

            List<SelectListItem> deger = (from x in db.uruns.ToList()
                                          select new SelectListItem
                                          {

                                              Text = x.UrunAd,
                                              Value = x.ID.ToString()

                                          }).ToList();
            List<SelectListItem> deger1 = (from x in db.carilers.ToList()
                                           select new SelectListItem
                                           {
                                               Text = x.CariAD + " " + x.CariSoyad,
                                               Value = x.CariID.ToString()
                                           }).ToList();
            List<SelectListItem> deger2 = (from x in db.personels.ToList()
                                           select new SelectListItem
                                           {
                                               Text = x.PersonelAd + " " + x.PersonelSoyad,
                                               Value = x.ID.ToString()
                                           }).ToList();

            ViewBag.dgr1 = deger1;
            ViewBag.dgr2 = deger2;
            ViewBag.dgr = deger;
            var veri = db.satisHarekets.Find(id);
            return View("SatisGetir",veri);
        }
        public ActionResult Satisguncelle(SatisHareket p)
        {
            var deger = db.satisHarekets.Find(p.SatisİD);
            deger.CariID= p.CariID;
            deger.Adet= p.Adet;
            deger.Fiyat= p.Fiyat;
            deger.PersonelID= p.PersonelID;
            deger.Tarih= p.Tarih;
            deger.ToplamTutar= p.ToplamTutar;
            deger.UrunID= p.UrunID;
            db.SaveChanges();
            return RedirectToAction("Index");
        }

        public ActionResult SatisDetay(int id)
        {
            var deger = db.satisHarekets.Where(x => x.SatisİD == id).ToList();

            return View(deger);
        }
    }
}

MVC-ModMaZa/Views/Satis/Index.cshtml
@using MVC_ModMaZa.Models.DbSınıflar
@model List<SatisHareket>
@{
    ViewBag.Title = "Index";
    Layout = "~/Views/Shared/_AdminLayout.cshtml";
}



<table id="tbl1" class="table table-bordered" style="margin-top:20px; ">
    <thead>
        <tr>
            <th>
                ID
            </th>
            <th>
                Ürün
            <th>
                Cari
            <th>
                Personel
            </th>
            <th>
                Adet
            </th>
            <th>
                Fiyat
            <th>
                Toplam
            </th>
            <th>
                Tarih

            </th>
            <th>
                Güncelle
            </th>
            <th>
                Detaylar
            </th>

        </tr>
        ,
    </thead>
    @foreach (var item in Model)
    {


        <tr>
            <td> @item.SatisİD </td>
            <td> @item.urun.UrunAd </td>
            <td> @item.cariler.CariAD @item.cariler.CariSoyad </td>
            <td> @item.personel.PersonelAd @item.personel.PersonelSoyad </td>
            <td> @item.Adet </td>
            <td> @item.Fiyat </td>
            <td> @item.ToplamTutar </td>
            <td> @item.Tarih </td>


            <td>
                <a href="/Satis/SatisGetir/@item.SatisİD" class="btn btn-success">Güncelle</a>
            </td>
            <td>
                <a href="/Satis/SatisDetay/@item.SatisİD" class="btn btn btn-outline-primary">Detaylar</a>
            </td>
        </tr>

    }

</table>
<a href="/Satis/YeniSatiş" class="btn btn-info">Yeni Satış Yap</a>

<link href="~/Content/bootstrap.css" rel="stylesheet" />

<script src="//ajax.googleapis.com/ajax/libs/jquery/1.11.1/jquery.min.js"></script>

<link href="https://cdn.datatables.net/1.10.15/css/dataTables.bootstrap.min.css" rel="stylesheet" />
<link href="https://cdn.datatables.net/responsive/2.1.1/css/responsive.bootstrap.min.css" rel="stylesheet" />
<script src="https://cdn.datatables.net/1.10.15/js/jquery.dataTables.min.js"></script>
<script src="https://cdn.datatables.net/1.10.15/js/dataTables.bootstrap4.min.js "></script>

<script>
    $('#tbl1').dataTable({});
</script>

MVC-ModMaZa/Views/Satis/SatisDetay.cshtml
@using MVC_ModMaZa.Models.DbSınıflar
@model List<SatisHareket>
@{
    ViewBag.Title = "SatisDetay";
    Layout = "~/Views/Shared/_AdminLayout.cshtml";
}

<h2>SatisDetay</h2>

<br />
<h2>Departman Personel Satış</h2>
<br />
<ol class="breadcrumb mb-4">
    <li class="breadcrumb-item active">Personel Adı: @ViewBag.pisim</li>
</ol>
<table class="table table-condensed">
    <tr>
        <th>SatışID</th>
        <th>Ürün</th>
        <th>Cari</th>
        <th>Personel</th>
        
        <th>Fiyat</th>
        <th>Adet</th>
        <th>Toplam</th>
        <th>Tarih</th>
        <th>Yazdır</th>
    </tr>
    @foreach (var item in Model)
    {
        <tr>
            <td>@item.SatisİD</td>
            <td>@item.urun.UrunAd</td>
            <td>@item.cariler.CariAD @item.cariler.CariSoyad</td>
            <td> @item.personel.PersonelAd @item.personel.PersonelSoyad </td>
            <td>@item.Fiyat</td>
            <td>@item.Adet</td>
            <td>@item.ToplamTutar</td>
            <td>@item.Tarih</td>
            <td> <a href="#" class="btn btn-default" style="background-color:dodgerblue">Yazdır</a>    </td>
        </tr>
    }
</table>

MVC-ModMaZa/Views/Satis/SatisGetir.cshtml
@model MVC_ModMaZa.Models.DbSınıflar.SatisHareket
@{
    ViewBag.Title = "SatisGetir";
    Layout = "~/Views/Shared/_AdminLayout.cshtml";
}
<br />
<h2>Satış Güncelle </h2>
<br />

@using (Html.BeginForm("Satisguncelle", "Satis", FormMethod.Post))
{
    @Html.HiddenFor(x => x.SatisİD)
    <h4>Ürün </h4>
    @Html.DropDownListFor(x => x.UrunID, (List<SelectListItem>)ViewBag.dgr, new { @class = "form-control" })
    <br />
    <h4>Cari</h4>
    @Html.DropDownListFor(x => x.CariID, (List<SelectListItem>)ViewBag.dgr1, new { @class = "form-control" })
    <br />
    <h4> Personel</h4>
    @Html.DropDownListFor(x => x.PersonelID, (List<SelectListItem>)ViewBag.dgr2, new { @class = "form-control" })

    <br />
    <h4>Adet</h4>
    @Html.TextBoxFor(x => x.Adet, new { @class = "form-control" })
    <br />
    <h4> Fiyat</h4>
    @Html.TextBoxFor(x => x.Fiyat, new { @class = "form-control" })
    <br />
    <h4>Toplam Tutar</h4>
    @Html.TextBoxFor(x => x.ToplamTutar, new { @class = "form-control" })
    <br />
    <h4>Tarih</h4>
    @Html.TextBoxFor(x => x.Tarih, new { @class = "form-control" })
    <br />
    <button class=" btn btn-warning"> Güncelle   </button>

}

MVC-ModMaZa/Views/Satis/YeniSatiş.cshtml
@model MVC_ModMaZa.Models.DbSınıflar.SatisHareket 
@{
    ViewBag.Title = "YeniSatiş";
    Layout = "~/Views/Shared/_AdminLayout.cshtml";
}
<br />
<h2>Yeni Satış Sayfası</h2>
<br />

<form class="form-group" method="post">
    <h4>Ürün </h4>
    @Html.DropDownListFor(x => x.UrunID, (List<SelectListItem>)ViewBag.dgr, new { @class = "form-control" })
    <br />
    <h4>Cari</h4>
    @Html.DropDownListFor(x => x.CariID, (List<SelectListItem>)ViewBag.dgr1, new { @class = "form-control" })
    <br />
    <h4> Personel</h4>
    @Html.DropDownListFor(x => x.PersonelID, (List<SelectListItem>)ViewBag.dgr2, new { @class = "form-control" })
    <br />
    <h4>Adet</h4>
    @Html.TextBoxFor(x => x.Adet, new { @class = "form-control" })
    <br />
    <h4>Fiyat</h4>
    @Html.TextBoxFor(x => x.Fiyat, new { @class = "form-control" })
    <br />
    <h4>Toplam Tutar</h4>
    @Html.TextBoxFor(x => x.ToplamTutar, new { @class = "form-control" })
    <br />
    <button class=" btn btn-primary"> Kaydet   </button>
</form>